### ISSUE TITLE
circle pattern

### ISSUE THREAD

**Issue by Jerikk07** [JSJBDEV/pirates#1]
Hello, 
how could we change the config value, for exemple, double the circle radius?

**Comment by ttramdriver** [comment]
in "config" in ".minecraft" [or wherever your instance of minecraft is saved] you should find a folder called "pirates", inside that folder should be a folder called "patterns" and there you should find a "circle.pattern", open it with notepad and there you can edit it. tho idk how the config works because i didnt make the mod but i think you can experiment with it by changing different values and tryign to get something closest to your wantings

tho id like to know what value does what, so if you find out please tell !!!!

**Comment by JSJBDEV** [comment]
Sorry I never responded to this I seem to miss notifications.

Yes pretty much what you say, 
The values are impulse values of directions applied to the ship and for how long untill it changes direction again basically

**Comment by JSJBDEV** [comment]
From pattern professor

```/**
     * A pattern is any combination of impulses to supply to the MotionInvokingBlock
     * forward 1 0
     * left 0.05 10
     * this is the equivalent to, impulse forward and left at the same time, then wait 10 ticks
     */```

**Comment by ttramdriver** [comment]
thanks for explaining!

**Comment by JSJBDEV** [comment]
as of version past 1.3.0, patterns are deprecated in favor of actual pathfinding, they may be kept in some regard for map makers

**Comment by ttramdriver** [comment]
yo awesome
